export const INCREMENT = 'INCREMENT'

export const DECREMENT = 'DECREMENT'

export const ASYNC_INCREMENT = 'ASYNC_INCREMENT'

export const UPDATEHOMELIST = 'UPDATEHOMELIST' 

export const UPDATECURHOME = 'UPDATECURHOME'

export const UPDATECURROOM = 'UPDATECURROOM'

export const UPDATECURROOMLIST = 'UPDATECURROOMLIST'

export const WXUSERINFO = 'WXUSERINFO'

export const CHANGEADDROOMLIST = 'CHANGEADDROOMLIST'

export const CHANGESCENEINFO = 'CHANGESCENEINFO'

export const CHANGEAUTOMATIONINFO = 'CHANGEAUTOMATIONINFO'