export const INCREMENT = 'INCREMENT'

export const DECREMENT = 'DECREMENT'

export const ASYNC_INCREMENT = 'ASYNC_INCREMENT'

export const CHANGEADDROOMLIST = 'CHANGEADDROOMLIST'

export const CHANGESCENEINFO = 'CHANGESCENEINFO'

export const CHANGEAUTOMATIONINFO = 'CHANGEAUTOMATIONINFO'